SRI-International/QC-App-Oriented-Benchmarks

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Added two files for public github release. We need to add an email/contact information for code of conduct violations. **This PR should not be merged until we have found a way to address this**. We could create an email for the sole purpose of tracking any reports, but I don't know what would be the best way.
The contributing file is also a pretty rough sketch of how someone might contribute, but I am open to suggestions as to how we could potentially modify this file to be more in-line with better contribution ideas. Additionally, we can always update the contributions file as more people start using the repo.
> Add `CONTRIBUTING` file and `CODE_OF_CONDUCT` file

- _common/qiskit/execute.py
This change was implemented as part if Issue #8.
It changes the default behavior of the Qiskit execution to recognize backends beginning with ibm_ or ibmq_ and applies optimization level 3, and the 'sabre' layout ... as suggested by IBM
> Use 'sabre' layout when executing on IBM hardware backends

- _setup/braket/README.md
- _setup/cirq/README.md
- _setup/qiskit/README.md
Added information about what versions of the software we tested the repo on, as well as ensured that all packages are installed if someone is using miniconda. I ran into errors when installing with the previous instructions, but these new instructions allowed me to create environments and immediately run the jupyter notebooks.
> Updated `_setup` READMES

- _common/qiskit/execute.py
This PR lets users pass arbitrary kwargs all the way to the backend's `run` method
> pass kwargs to run

- hamiltonian-simulation/braket/hamiltonian_simulation_benchmark.py
- hamiltonian-simulation/cirq/hamiltonian_simulation_benchmark.py
- hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py
When running any of the Hamiltonian simulation benchmarks from the command line the user would get a `FileNotFoundError`. This was due to a incorrect path to the `precalculated_data.json` files. 
Using the same structure as in the `vqe` benchmark, that also uses precalculated data, I fixed the path issue. The Hamiltonian simulation benchmarks now work as expected when executed on both the command line and jupyter notebooks.
> Fixed `FileNotFoundError`

- benchmarks-braket.ipynb.template
- benchmarks-cirq.ipynb.template
- benchmarks-qiskit.ipynb.template
Reduced size of markdown headings and moved the method type into the same md cell as the benchmark title.
> Switched md headings to H2

- _common/transformers/tket_optimiser.py
If backend is a simulator then `coupling_map=None` and results in the follow error:
```
File "_common/transformers/tket_optimiser.py", line 104, in quick_optimisation
arch = Architecture(coupling_map)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
1. pytket._tket.architecture.Architecture(connections: List[Tuple[int, int]])
2. pytket._tket.architecture.Architecture(connections: List[Tuple[pytket._tket.circuit.Node, pytket._tket.circuit.Node]])
```
Mentioning Daniel (@daniel-mills-cqc) so he can stay in the loop.
> Fixed `coupling_map` issue

- _common/metrics.py
- maxcut/qiskit/maxcut_benchmark.py
- New sets of functions added to maxcut_benchmark
- To use the new functionality, simply use load_data_and_plot(folder) from maxcut_benchmarks, where folder denotes the location where all the json files are located.
- Slight modifications to metrics.py 
- Added (s) to x axis label
- Within optgap plot code. New code to ensure that group_metrics_2 metrics are arranged in ascending order of circuit widths. (Note: circuit_metrics_detail_2.keys() may not necessarily be arranged in ascending order.)
- Instead of storing the final qiskit counts object, store the following values for the last iteration of each problem:
- 'cuts', a list of measured bitstrigs
- 'counts', a list of measurement counts
- 'sizes', a list of corresponding cut sizes
- Also store the best cut value for each iteration …
> Added functionality to load and plot using stored data from previous runs

- maxcut/qiskit/benchmarks-qiskit-add-maxcut.ipynb
* Added second cell from `benchmarks-qiskit.ipynb` for consistency
* Added `backend_id`, `hub`, `group`, `project`, `provider_backend`, `exec_options` arguments to all `run` calls to support alternate backends.
> Updated maxcut benchmark notebook

- maxcut/qiskit/maxcut_benchmark.py
Qiskit measurement results are reported in a little-endian format. Previous benchmark version assumed a big-endian format, which resulted in incorrect results.
Instead of reversing the bitstrings everywhere, this fix simple defines the qaoa circuit as a "water image" of what it was before.
> fix qaoa bug: endianness issue

- maxcut/qiskit/maxcut_benchmark.py
- maxcut/qiskit/maxcut_runtime3.ipynb
- maxcut/qiskit/runtime_utils.py
After submitting a job to runtime a file will be created with the job id and status of that job. If the user tries to run on that same backend again it will prompt user on if they want to overwrite their data. If yes then it will submit a new job, if no, it will wait for previously submitted job to finish and save/plot the results.
Had to remove an assertion put in by Pratik. It asserted that all files within a backend directory must start with `width`. This will not work with this implementation because the job file will also be stored in the backend directory.
> Added Job Handling to Runtime

- _common/metrics.py
- maxcut/qiskit/benchmarks-qiskit-add-maxcut.ipynb
- Detailed optgaps: put abs(....) for every objective function while plotting optgaps. (Sometimes some of the metrics have optgap values of "-0.0", which used to interpreted by matplotlib as being negative and hence not shown by on the plot. This will not happen now)
- cut size distributions will not skip over cut sizes with 0 counts.
- ylim changed back to 0 to 100 for detailed optgaps, since some of the metrics do have large values especially at smaller graph sizes.
- Parameter changes in notebook.
- Replaced maxn by gibbs cells.
- Removed restarts cell in notebook, since it was outdated, and the latest code is now in
> optgaps plot improvements; changes to notebook

- _common/maxcut.mplstyle
- _common/metrics.py
- maxcut/qiskit/auxiliary_functions.py
- maxcut/qiskit/maxcut_benchmark.py
- changed metrics.maxcut_inputs to maxcut_benchmark.maxcut_inputs in auxiliary_functions
- removed upper limit of 10 on restarts
- created a new function called get_distribution_and_stats in metrics. This function processes circuit metrics and creates data that is used for plotting
- Made changes to plot_cutsize_distribution. Previously, distributions for multiple widths were plotted on in a single figure. Now, each width gets a separate figure.
- Additionally, also plotting AR, bestcut ratio, gibbs ratio and CVaR ratio in the distribution plot
> changes to cut-size distribution, etc.

- hydrogen-lattice/qiskit/benchmarks-qiskit-hydrogen-lattice.ipynb
Note!  The name of the main notebook in the hydrogen lattice folder has changed
> Change hydrogen lattice plot_layout_style to 'grid' default

- _common/metrics.py
- hydrogen-lattice/qiskit/hydrogen_lattice_benchmark.py
(probably due to queue time)
Remove later, if we get rid of queue times early
> For area plots, remove exceedingly long initial elapsed times

- _common/metrics.py
- _common/qiskit/execute.py
We now switch to log scale at a certain range
For IBM Sampler executions, use quantum_seconds for the execution time.
> Improvements to metrics bar plot and IBM Sampler exec time

- _common/qiskit/execute.py
Cannot use IBM!.load_account() for authentication. The IBMQ provider object cannot be used for circuit-runner.
> Changes to qiskit/execute.py to support IBM Cloud

- hhl/qiskit/benchmarks-qiskit-hhl.ipynb
- hhl/qiskit/hhl_benchmark.py
The hhl_benchmark.min_register_qubits variable defaults to 1 but can be overridden
> Add HHL option to set min number of qubits for input and clock registers

- maxcut/qiskit/auxiliary_functions.py
- maxcut/qiskit/maxcut_benchmark.py
From https://docs.astral.sh/ruff/
> The Ruff formatter is an extremely fast Python code formatter designed as a drop-in replacement for [Black](https://pypi.org/project/black/), available as part of the ruff CLI via ruff format.
> 
> The Ruff formatter is available as a [production-ready Beta](https://astral.sh/blog/the-ruff-formatter) as of Ruff v0.1.2.
Ruff is orders of magnitude faster than Autoflake, Flake8, Pyflakes, Pycodestyle, Pylint. It is used by major projects such as Apache Airflow, FastAPI, Hugging Face, pandas, SciPy. As such, I think is a good addition to the repo to keep the code clean.
> ruff: Apply ruff --fix maxcut/qiskit/

- .pre-commit-config.yaml
I don't exactly remember how to enable pre-commit in a GH repo (https://pre-commit.com/#plugins) but it should look like this: https://results.pre-commit.ci/run/github/42205414/1705017304.m3mnZTHiQ3eC9mW3YS30Iw.
> Add pre-commit containing ruff linter

- _common/metrics.py
- _common/ocean/execute.py
Turn num_sweeps into type int on line 201 in _common\ocean\execute.py , allowing the ocean maxcut benchmark to run. Completed in python 3.9.7 and the venv specified in _setup\ocean, numpy version I got here was version 1.26.3 .
> Fix ocean maxcut bug

- _common/qiskit/execute.py
- _setup/qiskit/README.md
- amplitude-estimation/qiskit/ae_benchmark.py
- hhl/qiskit/sparse_Ham_sim.py
- hhl/qiskit/uniform_controlled_rotation.py
- hydrogen-lattice/Dev/Main_opt.py
- hydrogen-lattice/qiskit/hydrogen_lattice_benchmark.py
- image-recognition/Dev/image_recog_QCNN 4 qubit Version.py
- image-recognition/Dev/image_recog_QCNN Visualize.py
- image-recognition/Dev/image_recog_QCNN_8qubit Version.py
- image-recognition/README.md
- image-recognition/qiskit/image_recognition_benchmark.py
- maxcut/ocean/maxcut_benchmark.py
- maxcut/qiskit/benchmarks-qiskit-maxcut.ipynb
- maxcut/qiskit/maxcut_benchmark.py
- maxcut/qiskit/qiskit-parameters-example.ipynb
- vqe/qiskit/vqe_benchmark.py
These changes address issued identified by users when executing against Qiskit version 1.0.
Most benchmarks work, except vqe and image-recognition, which use opflow (now deprecated).
> Merge code changes to support the upgrade to qiskit 1.0

- hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py
- When using method=2 for ham sim, instead of checking fidelity with classically evolved hamiltonian, now check fidelity with distribution from a perfect quantum computer running the quantum ham sim circuit.
> Ham sim method=2 changes

- bernstein-vazirani/qiskit/bv_benchmark.py
It was very slow above 25 qubits due to the use of numpy.random.choice()
> For BV, improve performance of random scret integer generation

- hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py
- hamiltonian-simulation/qiskit/hamiltonian_simulation_kernel.py
saved circuit needs to be cleared after printing, so it doesn't incorrectly draw if hamiltonian class changed
> Fix issue with printing of ham sim circuits

- bernstein-vazirani/qiskit/bv_benchmark.py
Earlier in bernstein-vazirani method-2, the qubits appended using mid_circuit_qubit_group.append(2) was appending 17 times due to present inside the loop. After the changes done, it will append only required number of qubits.
***Screenshots from the json file are attached for reference.
> bv_benchmark.py: make the append of mid_circuit_qubit_group out of the loop

- _common/braket/execute.py
- phase-estimation/braket/pe_benchmark.py
In Braket's execute.py, functions were added to obtain circuit metrics such as qc_depth, qc_size, and qc_count_ops. The same values were used for the transpiled metrics as those calculated for the circuit metrics.
Screenshots from the benchmarks are attached for reference.
> Braket: able to get volumetric positioning plots

- hamlib/benchmark_hamlib_observables_custom-group.ipynb
- hamlib/generate_pauli_groups.py
In `generate_pauli_groups.py`, it contains all the functions to generate k-commuting groups, which do not depend on Cirq, Openfermion, or Qiskit.
In `benchmark_hamlib_observables_custom-group.ipynb`, it uses 
`from generate_pauli_groups import compute_groups`
to generate commuting groups.
> Get rid of Cirq, Openfermion, and Qiskit in grouping method

- _setup/qiskit/README.md
In `_setup/qiskit/README.md`, added a paragraph on configuring execution options for Qiskit Runtime primitives.
> Add a paragraph on configuring execution options for Qiskit Runtime primitives

- _common/cudaq/execute.py
- _common/metrics.py
- _common/qcb_mpi.py
- hamlib/_common/hamlib_utils.py
- hamlib/hamlib_simulation_benchmark.py
- phase-estimation/pe_benchmark.py
- quantum-fourier-transform/qft_benchmark.py
This adds initial MPI simulation support to the observables-work branch for QPE, QFT, and Hamlib benchmarks.
MPI is enabled by loading the mpi4py module when invoking python. E.g. `python3 qft_benchmark.py -a cudaq -n 33 -c 1` would become `mpirun -np 2 python3 -m mpi4py qft_benchmark.py -a cudaq -s 1000 -n 33 -c 1`
When the mpi4py module is not loaded, stub functions are used for single-process execution as before without any requirement for an MPI library.
stdout is captured for all but the leader MPI task to avoid duplicate output.
> Add MPI support for QPE, QFT, and Hamlib

- _common/qiskit/execute.py
- hhl/qiskit/hhl_benchmark.py
- shors/qiskit/shors_benchmark.py
This PR includes changes to support Qiskit 2.0
- add new backend_id "aer_sampler" to test circuits with mid-circuit measurement locally
- join sampler results for all classical bits to support benchmarks with multiple classical registers (e.g., HHL)
- show an error message if an error occurred during `job.result()` (such as error during real device execution)
- fix `transpiler_seed` to make benchmarks reproducible
- fix HHL benchmark to deal with SamplerV2 result (i.e., no white space between classical registers)
- replace `c_if` with `if_test` because Qiskit 2 removed `c_if`.
I discovered an issue #692.
> Support Qiskit 2

- _common/qiskit/execute.py
This PR is WIP because this depends on #691.
This PR is also for discussion purpose because there is an existing approach.
https://github.com/SRI-International/QC-App-Oriented-Benchmarks/blob/master/_common/postprocessors/mthree/mthree_em.py
This PR added a new option to support M3 mitigation to improve measurement error correction.
This includes new global variables (`use_m3`, `m3_mitigation`, `m3_cache`) and logic to calibrate and cache M3 mitigators during circuit execution.
Calibration data is reused if some circuits use the same qubits.
M3 calibration is invoked in sessions or batches to reduce queue time.
This PR introduces a new option despite the following existing approach because it’s challenging to utilize session and batch.
> Add a new M3 option

- phase-estimation/pe_benchmark.py
The purpose of this pull request is to modify the Phase-Estimation benchmark to optionally return Qiskit circuits.
1. Added get_circuits flag to the run method.
2. Added a variable to store circuits
3. Added an early return to avoid executing circuits.
- phase-estimation/pe_benchmark.py
- Circuits are returned as `list[QuantumCircuit]`
- Circuit information is returned using the metrics module.
> Get Phase-Estimation Qiskit Circuits

- quantum-fourier-transform/cudaq/qft_kernel.py
Added an argument use_midcircuit_measurement in the quantum-fourier-transformation/cudaq/qft_kernel.py such that it supports dynamic circuit changes made in quantum-fourier-transformation/qiskit/qft_kernel.py
Note: Work still yet to be done such that cudaq handles dynamic circuit.
> Add argument to QFT cudaq kernel for dynamic circuits

- bernstein-vazirani/bv_benchmark.py
1. Changed `all_qcs` from a list to a dictionary.
2. Added sub dictionaries to `all_qcs` to match the structure of `metrics.circuit_metrics`.
3. Returning `metrics.circuit_metrics` instead of the module.
The returned circuits are `dict[str, dict[str, QuantumCircuit]]` and the information is returned as `dict[str, dict[str, dict[str, float]]]`.
> New Structure For Returned Bernstein-Vazirani Circuits

- quantum-fourier-transform/qft_benchmark.py
1. Changed `all_qcs` from a list to a dictionary.
2. Added sub dictionaries to `all_qcs` to match the structure of `metrics.circuit_metrics`.
3. Returning `metrics.circuit_metrics`.
The returned circuits are `dict[str, dict[str, QuantumCircuit]]` and the information is returned as `dict[str, dict[str, dict[str, float]]]`.
> Getting Quantum-Fourier-Transform Circuits

- benchmarks-braket.ipynb
- benchmarks-cirq.ipynb
- bernstein_vazirani/braket/bv_benchmark.py
- bernstein_vazirani/cirq/bv_benchmark.py
- hidden_shift/braket/hs_benchmark.py
- hidden_shift/cirq/hs_benchmark.py
- phase_estimation/braket/pe_benchmark.py
- phase_estimation/cirq/pe_benchmark.py
- quantum_fourier_transform/braket/qft_benchmark.py
- quantum_fourier_transform/cirq/qft_benchmark.py
The mentioned benchmarks only use the new package structure for Qiskit and CUDA-Q; this PR extends their package structure to Cirq and Braket -- updating their respective notebooks as well. Moving forward in this manner will allow for a smooth merge into master at the end. 
- All benchmarks executed in _benchmarks-cirq.ipynb_. 
- Assumed functionality in Braket.
> New imports for BV, PE, HS, and QFT for Cirq and Braket

- deutsch-jozsa/dj_benchmark.py
- grovers/grovers_benchmark.py
Added the `get_circuits` flag to DJ and Grover's to support modularizing the benchmarking suite. Also fixed DJ, it was missing the call to `qedc_benchmark_init()` and was causing an import error. 
Ran both benchmarks with `get_circuits=True` in `benchmarks-qiskit.ipynb`; successfully obtained circuits and metrics.
> Adding `get_circuits` Flag to DJ and Grover's

- _setup/cudaq/README.md
NVIDIA made breaking changes in 0.12 from 0.10.
This PR makes code changes in the HamLib benchmark so that it works properly with the modified SpinOperator API of 0.12
> Merge HamLib changes for CUDAQ 0.12 from master to develop

- _common/qiskit/execute.py
This file contains some chunk of codes written within the comments ######@@@@@@@@@@@@###########.
This execute.py file now supports both dynamical decoupling and dynamic circuits on an IBM Hardware device. This requires setting the exec_options in the benchmarks-qiskit.ipynb as:
exec_options = {
"use_ibm_quantum_platform": False,
"use_sessions": False,
"dynamical_decoupling": True,
"dynamic_circuit": False
}
> Execute file supporting dynamic circuits and dynamical decoupling

- _common/cudaq/execute.py
- bernstein-vazirani/bv_benchmark.py
- hamlib/hamlib_simulation_benchmark.py
- hidden-shift/hs_benchmark.py
- phase-estimation/pe_benchmark.py
- quantum-fourier-transform/qft_benchmark.py
This PR introduces support for passing additional backend execution options to benchmark scripts. The CUDA-Q backend setup logic in `_common/cudaq/execute.py` has also been updated to handle these options, including robust parsing and validation.
* Added `--exec_options` argument to the argument parsers in the following benchmark scripts, allowing users to specify additional backend options as a JSON string and updated the logic to forward the user-supplied options instead of an empty dictionary:
1.  `bv_benchmark.py`,
2.  `hamlib_simulation_benchmark.py`, 
3. `hs_benchmark.py`, 
4. `pe_benchmark.py`, 
5. `qft_benchmark.py`
* Modified `_common/cudaq/execute.py` to parse `exec_options` as JSON, validate key/value types, and gracefully fall back to defaults if parsing fails.
* Imported the …
> Use `exec_options` to pass backend-specific arguments to CUDA-Q's `set_target`
