_setup/braket/README.md, amplitude-estimation/README.md, bernstein-vazirani/README.md, deutsch-jozsa/README.md, hamiltonian-simulation/README.md, vqe/README.md
README changes. There is still more work to do on READMEs, but this makes good progress.
- Added more explicit comparison to grover's in AE README
- Added citations for VQE uses in intro
- Small changes based on Arun's comments
- Made HamSim only running a single circuit more explicit
=> Readme updates

_common/qiskit/execute.py, amplitude-estimation/qiskit/ae_benchmark.py, bernstein-vazirani/qiskit/bv_benchmark.py, deutsch-jozsa/qiskit/dj_benchmark.py, grovers/qiskit/grovers_benchmark.py, hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py, hidden-shift/qiskit/hs_benchmark.py, monte-carlo/qiskit/mc_benchmark.py, phase-estimation/qiskit/pe_benchmark.py, quantum-fourier-transform/qiskit/qft_benchmark.py, shors/qiskit/shors_benchmark.py, vqe/qiskit/vqe_benchmark.py
(optimization_level, layout_method, routing method)
=> Provide mechanism to configure compilation options

_common/transformers/README-CQ.md, _common/transformers/tket_optimiser.py
Here we add two new transformers, built using TKET optimisation passes.
=> Add Tket transforms

_setup/README.md, _setup/braket/README.md, _setup/cirq/README.md, _setup/qiskit/README.md
- Put general information about conda environments in  `_setup/README.md`. 
- Deleted common environment information from each SDK directory. 
- Added information on `pip show pip` to ensure environment is working correctly
=> Updated _setup/README.md and relevant SDK READMEs

_common/transformers/tket_optimiser.py
This pull request makes minor changes to align with the recent upgrade of pytket.
=> Upgrade to pytket 1.0

benchmarks-braket.ipynb.template, benchmarks-cirq.ipynb.template, benchmarks-qiskit.ipynb.template
Also added a header for the combined benchmarking results.
=> Changed headings to H3

_common/qiskit/execute.py
Original code from [miamico](https://github.com/miamico), slightly modified to conform to current code style. 
Original commit message (also from [miamico](https://github.com/miamico)): 
"Modify `execute.py` module for qiskit to allow multiple transpilations passes for the transpiler. This is useful because the transpiled circuit is found stochastically and it can vary in different runs of the transpiler. Running the transpiler multiple times and selecting the transpiled circuit with the lowest cx count can improve the fidelity of circuit ran with qiskit."
=> Add multi transpile code

maxcut/qiskit/maxcut_benchmark.py
Added custom theta initialization parameter `custom_theta_init: dict[float]`. To initialize custom angles, pass a dict of floats with the angle as key, e.g. 
`maxcut_benchmark.run(custom_theta_init={"beta": 0.5, "gamma": 0.5})`
Slightly refactored code to initialize new thetas in main loop, this means we no longer need the `method` and `rounds` parameters in `MaxCut` since we always pass `thetas_init`. 
Also, fixed title issue in optimality gap plot (was missing the `f` for the fstring).
=> Added custom theta initialization & small refactor

maxcut/qiskit/maxcut_benchmark.py
Changed parameter string to use actual Greek characters 𝞫 and 𝞬
=> Changed parameter string values

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
Also changed optimality gap to %., and changed the name under which the optgap plot will be saved
=> Plotting quartile optimality plots over bar plots

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
New code to save the results as soon as they become available for each pair of values of (num_qubits, graph degree).
=> Saving metrics to json files

_common/metrics.py, _common/plots_template.mplstyle, maxcut/qiskit/maxcut_benchmark.py
- Added function to metrics.py for computing the empirical probability distribution of cut sizes.
- Added function that plots the cactus plots
- Added an mplstyle file
- Rather than using mplstyle globally, using it with a context manager
- Restructuring in plot_metrics_optgaps to allow choosing which metrics to plot.
=> more changes to optgap plotting

_common/maxcut.mplstyle, _common/metrics.py
Changes to mplstyle file...
If one wants to use the LaTeX font, they can simply uncomment the corresponding lines in the mplstyle file.
=> Removed LaTeX font for figures

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
- Set title for ECDF plot to "Cumulative Distribution (ECDF) - "
- Approx ratio will now appear above max N in the optgap legend
- Area plot will be created before optgaps.
=> optgap legend sequence; ECDF title change, etc

_common/metrics.py, maxcut/qiskit/benchmarks-qiskit-add-maxcut.ipynb, maxcut/qiskit/maxcut_benchmark.py
Changed to cut size/ max cut size, instead of approximation ratio
=> Maxcut_benchmarks cleanup, uniform sampling

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
Get distribution of cut sizes for uniform random sampling. Changes to metrics.py.
Next, will add a function for plotting empirical probability distribution of cut sizes, both for the QAOA output, and uniform random sampling.
=> Fixed opt time computation; Uniform random sampling for maxcut

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
Detailed optgaps plot is still there
=> Added optgaps barplots

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
Also moved bar plot to within optgap function, to reduce repetition of code.
=> Added quartiles to bar plot

_common/maxcut.mplstyle, _common/metrics.py
Also removed axes linewidth from mplstyle
=> Better names for saving area plots

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
changes to maxcut_benchmark and metrics.py
=> (1) Added Gibbs Objective function, (2) Polar plots (3) Reduce memory usage/json size

maxcut/qiskit/benchmarks-qiskit-add-maxcut.ipynb
=> Added random restarts cell to notebook

_common/qiskit/execute.py, maxcut/qiskit/maxcut_benchmark.py, maxcut/qiskit/maxcut_runtime.ipynb
* Added logger to help keep track of code behavior
* Added parameter implementation
* Fixed merge conflicts
=> Added logger and parameters

_common/qiskit/execute.py
small fix to make transformers apply to all circuits (and not just the first one)
=> changed reference to backend_exec_options in execute.py

_common/metrics.py, maxcut/qiskit/maxcut_benchmark.py
change save location for qiskit runtime
=> Restarts looping; Location change for width files

maxcut/qiskit/maxcut_benchmark.py
Previous version of the function did not behave correctly in some cases. Fixed now.
=> Corrections to get_restart_angles()

maxcut/_common/common.py
Correctly process instance solution. Originally was reading problem data instead of solution data.
=> Fixed read instance solution bug

maxcut/qiskit/maxcut_runtime.ipynb, maxcut/qiskit/runtime_utils.py
Cleaned up notebook by moving prepare instances code to `runtime_utils.py`
=> Update notebook and runtime utils

_common/maxcut.mplstyle, maxcut/qiskit/benchmarks-qiskit-add-maxcut.ipynb, maxcut/qiskit/maxcut_benchmark.py
-restart angkes default to all 1's
- default values of thetas_array and max_circuits are both None now in run()
- removed ex.set_execution_target within the load functions
- Number of restarts will be shown in the title of figures now. -white background color in mplstyle
=> default angles changed, plot titles includes restarts=, etc.

maxcut/qiskit/maxcut_runtime2.ipynb
Add second runtime notebook without any references to the old ibm provider (IBMQ). Instead uses `QiskitRuntimeService`
=> Add maxcut_runtime2

maxcut/qiskit/maxcut_runtime2.ipynb, maxcut/qiskit/maxcut_runtime3.ipynb, maxcut/qiskit/runtime_utils.py
* Updated maxcut_runtime notebooks 2 and 3
* Fixed program id issue in runtime_utils
* Fixed regex error in runtime_utils
=> Fix various bugs

maxcut/qiskit/maxcut_runtime2.ipynb
* Made interactive flag default to True
* Delete print statement used for debugging
=> Cleaned up runtime2

maxcut/qiskit/maxcut_benchmark.py
Removed "hub", "group", "project" and "backend_provider" from stored calues
=> do not store 'hub' etc. in json file.

_common/transformers/trueq_rc.py
This PR contains various improvements to compilation in the True-Q transformer options
=> Updated True-Q transformer options by optimizing the compilers

_common/transformers/tket_optimiser.py, benchmarks-qiskit.ipynb.template
* Removed `qiskit.BaseBackend` type-hint from `tket_optimiser.py` as it is deprecated
* Removed qiskit pass-manager from notebook as it currently doesn't work
* Added `exec_options` for tket optimization in notebook
=> tket_update

_common/metrics.py
changed the link style. It is now pink, thick and faint, for consistency with the other plots.
=> cut size distribution: monkey plot style changed

README.md, _common/qiskit/benchmark_runner.py
As per discussions with @rtvuser1 and @WrathfulSpatula, there is now a generalized benchmark runner script for Qiskit. 
I iterated on a few different ways to do this given the present infrastructure and felt this was most likely the cleanest approach that doesn't alter any of the other files. 
Let @WrathfulSpatula and myself know if this is more inline with what you also had in mind, and thanks again for the discussion!
=> Adding generalized qiskit benchmark runner script.

_common/transformers/tket_optimiser.py
This PR adds a transformer which uses approximate q-qubit gate synthesis. Benchmarks have shown promising results using this method. I'm adding this now in part to ensure that those using approximate synthesis are talking about the same workflow.
=> Add approximate compilation

hydrogen-lattice/Dev/Main.py, hydrogen-lattice/Dev/ansatz.py, hydrogen-lattice/Dev/simulator.py
Initial changes for real Hamiltonian matrix
=> VQE Initial changes for Hamiltonian matrix

_common/qiskit/benchmark_runner.py
=> Correction to benchmark_runner provider_module_name and provider_class_name handling

_common/custom/custom_qiskit_noise_model.py, _common/metrics.py, _common/qiskit/execute.py
(add a .QV field to the nose model object for use in plots) Leave custom_noise_model at QV of 32 so it is easy to test
=> Change default noise model to 2048 and identify with QV number

hydrogen-lattice/qiskit/hydrogen_lattice_benchmark.py
Currently the Standalone VQE implementation (Main_OPT.py) has been successfully executed and optimized to reach the global minimum. Moving forward, the next step is to incorporate the changes made in the Standalone VQE into the existing framework used for implementing MaxCut.
The integration process will involve adapting the Standalone VQE code and incorporating it into the MaxCut framework. This includes modifying the necessary functions, classes, and parameters to ensure compatibility and seamless integration.
Current PR is an attempt to push the initial draft of VQE in an iterative framework..Currently, Code is not executable due to an integration issue where there is a Mismatching number of values and parameters and other bugs. Respective fixes and modifying optimization logic to be …
=> Initial draft of VQE Implementation in framework used for MaxCut

benchmarks-qiskit.ipynb.template
=> Remove MaxCut method=1 from top level benchmark notebook

_common/transformers/tket_optimiser.py
This PR clarifies some of the default pytket transformer parameters.
=> Clarify pytket defaults

image_recognition/Dev/expectation_calc.py, image_recognition/Dev/image_recog.py, image_recognition/Dev/image_recog_QCNN_Version.py, image_recognition/qiskit/image_recognition_benchmark.py
Minor correction for looping scaled data instead of pre processed data
=> Training and testing data format correction in loop

image_recognition/Dev/image_recog.py
File contains 4 qubit working model and preloading changes and mini batching changes are removed and saved in local version as they are under testing
=> Basic version of 4 qubit 

image_recognition/Dev/expectation_calc.py
Small changes in expectation calc
=> expectation file added

image_recognition/Dev/expectation_calc.py, image_recognition/Dev/expectation_calc_qcnn.py, image_recognition/Dev/image_recog_QCNN.py, image_recognition/Dev/image_recog_batch.py
Current commit has working version of image_recog around 90 % accuracy for 4 qubits and changes are in progress for 8 qubits and parallelly for implementing QCNN version with same architecture by changing variational circuit   (image_recog_QCNN.py) and current PR also has a stand alone version of batching execution which will be integrated together into one framework once model is fine tuned
=> Image recog

_common/metrics.py, hydrogen-lattice/_common/h_lattice_metrics.py, hydrogen-lattice/qiskit/hydrogen_lattice_benchmark.py
Added line plots and changed the precision parameter
=> Hydrogen lattice dev

_common/qiskit/execute.py, maxcut/qiskit/maxcut_benchmark.py
[Add result() to Local Job object to support executor immediate mode]
[In maxcut, do not store exec_options in data file]
=> Execution pipeline enhancements

_common/metrics.py
(this is the one used in our IEEE app-oriented benchmarks paper)
=> Use custom spectral colormap by default.

hydrogen-lattice/_common/h_lattice_metrics.py, hydrogen-lattice/qiskit/benchmarks-qiskit-hydrogen-lattice-extras.ipynb, hydrogen-lattice/qiskit/benchmarks-qiskit-hydrogen-lattice.ipynb, hydrogen-lattice/qiskit/hydrogen_lattice_benchmark.py
Note!  The name of the main notebook in the hydrogen lattice folder has changed
=> Merge latest from Hydrogen lattice branch

hydrogen-lattice/_common/h_lattice_metrics.py
(usually due to wait in the queue.)
=> Add simple technique to toss out long initial elapsed times

hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py, hamiltonian-simulation/qiskit/hamiltonian_simulation_kernel.py
Earlier problem: loop on mirror circuit
Fixed: used reverse inbuilt python to change the loop order for circuit.
Thanks to Sonny for helping with debugging.
Anish
=> Mirror circuit error fixed

hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py, hamiltonian-simulation/qiskit/hamiltonian_simulation_kernel.py
In this PR, I have create a QuasiHamiltonian mirror circuit implementation while the original Inverse Circuit is kept. 
If you want to use RandomPauli method for mirror circuit, use -ranp argument when you run the code.
Thanks,
Anish
=> Random Pauli applied for mirror circuit along with original inverse circuit kept

hamiltonian-simulation/README.md, hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py
Init state fixed with Readme updated.
=> Init state fixed with Readme updated.

hamlib/qiskit/hamlib_simulation_kernel.py
=> Comment out print of inverse as it is failing with Qiskit 1.1.

hamlib/qiskit/hamlib_simulation_benchmark.py, hamlib/qiskit/hamlib_simulation_kernel.py, hamlib/qiskit/hamlib_utils.py
Fix minor issue with printing of inverse circuit for method 3
=> Move initialization of kernel params out of hamlib, put into kernel_draw

hamiltonian-simulation/qiskit/hamiltonian_simulation_kernel.py, hamiltonian-simulation/qiskit/test_hamiltonian_simulation.py, hamlib/qiskit/hamlib_simulation_benchmark.py, hamlib/qiskit/hamlib_simulation_kernel.py, hamlib/qiskit/pygsti_mirror.py
Also fix broken tests in hamiltonian-simulation
=> More cleanup, and add pyGSTi code to create random Paulis

hamiltonian-simulation/qiskit/hamiltonian_simulation_benchmark.py, hamlib/qiskit/hamlib_simulation_benchmark.py
note: does not work for hamiltonian-simulation, since we use precalculated data
=> Add -steps and -time command line arguments -> K and t run() args

_common/cirq/execute.py, amplitude-estimation/cirq/ae_benchmark.py, bernstein-vazirani/cirq/bv_benchmark.py, deutsch-jozsa/cirq/dj_benchmark.py, grovers/cirq/grovers_benchmark.py, hamiltonian-simulation/cirq/hamiltonian_simulation_benchmark.py, hidden-shift/cirq/hs_benchmark.py, monte-carlo/cirq/mc_benchmark.py, phase-estimation/cirq/pe_benchmark.py, quantum-fourier-transform/cirq/qft_benchmark.py, shors/cirq/shors_benchmark.py
1. In execute.py, added functions to get transpiled metrics which helps to generate the Volumetric Positioning Plot
2. changes done in some benchmarks for proper calculation of counts and correct_dist in analyze_and_print_result()
***Screenshots from the benchmarks are attached for reference.
=> Cirq: Added functions to get transpiled metrics which helps to generate the Volumetric Positioning Plot

hamlib/qiskit/hamlib_vqe_meas_reduction.py
The measurement circuit cannot diagonalize the observable properly. I checked some other methods and they are not very stable. Need some help.
=> Add the script to calculate the expectation value for VQE using different measurement methods

hamlib/generate_pauli_groups.py
changed the "if_commute" check
=> test commutativity w/o constructing matrix rep

_common/qiskit/execute.py
Computes the circuit depth and gate counts and stores to metrics table
=> Add compute_and_store_circuit_info() to Qiskit execute

_common/qiskit/execute.py, deutsch-jozsa/dj_benchmark.py, deutsch-jozsa/qiskit/dj_kernel.py
Isolated DJ's qiskit implementation into DJ/dj_benchmark.py and DJ/qiskit/dj_kernel.py to support the kernel architecture in the QED-C repository.
=> Isolated DJ's qiskit implementation into DJ/dj_benchmark.py and DJ/qiskit/dj_kernel.py

phase-estimation/qiskit/pe_kernel.py
Fixed issue with measurement on PE kernel for dynamic circuits.
=> Fixed issue with measurement on PE kernel for dynamic circuits

deutsch_jozsa/dj_benchmark.py, deutsch_jozsa/qiskit/dj_kernel.py, grovers/grovers_benchmark.py, phase_estimation/qiskit/pe_kernel.py, quantum_fourier_transform/cudaq/qft_kernel.py, quantum_fourier_transform/qiskit/qft_kernel.py
Merged the `develop` branch with the `qedc-app-bms` branch. Also modified Grover's and DJ benchmarks to use imports instead of `sys.path`.
Ran Grover's, DJ, PE, and QFT in the _benchmarks-qiskit.ipynb_ file to ensure that there were no fatal errors.
=> Merge develop into qedc-app-bms

hamlib/cudaq/hamlib_simulation_kernel.py
- SpinOperator constructor signature
- Identity padding for missing terms
- Using only real part of the coefficients
cc @cuMikeBrown
=> Update the HamLib application to match CUDA-Q v0.12.0 APIs
